<?php
namespace LaraCall\Infrastructure\Repositories;

use LaraCall\Domain\Entities\State;
use LaraCall\Domain\Repositories\StateRepository;

/**
 * StateRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DoctrineStateRepository extends AbstractRepository implements StateRepository
{
    /**
     * @param array      $criteria
     * @param array|null $orderBy
     *
     * @throws \OutOfBoundsException If not found.
     *
     * @return State
     */
    public function getOneBy(array $criteria, array $orderBy = null)
    {
        if ($entity = parent::findOneBy($criteria, $orderBy)) {
            return $entity;
        }

        throw new \OutOfBoundsException(
            sprintf('State not exists by criteria. [criteria: %s]', implode(',', $criteria))
        );
    }
}
