<?php
namespace LaraCall\Infrastructure\Repositories;

use LaraCall\Domain\Entities\Country;
use LaraCall\Domain\Repositories\CountryRepository;

/**
 * CountryRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DoctrineCountryRepository extends AbstractRepository implements CountryRepository
{
    /**
     * @param array      $criteria
     * @param array|null $orderBy
     *
     * @throws \OutOfBoundsException If not found.
     *
     * @return Country
     */
    public function getOneBy(array $criteria, array $orderBy = null)
    {
        if ($entity = parent::findOneBy($criteria, $orderBy)) {
            return $entity;
        }

        $this->getEntityManager();
        throw new \OutOfBoundsException(
            sprintf('Country not exists by criteria. [criteria: %s]', implode(',', $criteria))
        );
    }
}
