<?php

namespace LaraCall\Infrastructure\Repositories;

use LaraCall\Domain\Entities\User;
use LaraCall\Domain\Repositories\UserRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DoctrineUserRepository extends AbstractRepository implements UserRepository
{
    /**
     * @param User $user
     *
     * @return mixed
     */
    public function save(User $user)
    {
        $this->_em->persist($user);
    }

    /**
     * @return void
     */
    public function commit()
    {
        $this->_em->flush();
    }

    /**
     * @param array $criteria
     * @param array $orderBy
     *
     * @throws \OutOfBoundsException If not found.
     * @return User
     */
    public function getOneBy(array $criteria, array $orderBy = null)
    {
        if ($entity = parent::findOneBy($criteria, $orderBy)){
            return $entity;
        }

        throw new \OutOfBoundsException(
            sprintf('USER not exists by criteria. [criteria: %s]', implode(',', $criteria))
        );
    }
}
